# Generated by Django 5.0.6 on 2024-05-19 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_method', models.CharField(max_length=100)),
                ('card_number', models.CharField(max_length=100)),
                ('card_holder', models.CharField(max_length=100)),
                ('expiry_date', models.CharField(max_length=100)),
                ('cvv', models.CharField(max_length=100)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.booking')),
            ],
        ),
    ]
