# Generated by Django 5.0.6 on 2024-05-20 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_profile_email_profile_username_alter_profile_bio_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
