# Generated by Django 5.0.6 on 2024-05-24 00:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_payment_card_number_alter_payment_cvv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='card_number',
            field=models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message='Card number must be 16 digits.', regex='^\\d{16}$')]),
        ),
        migrations.AlterField(
            model_name='payment',
            name='cvv',
            field=models.CharField(max_length=3, validators=[django.core.validators.RegexValidator(message='CVV must be 3 digits.', regex='^\\d{3}$')]),
        ),
        migrations.AlterField(
            model_name='payment',
            name='expiry_date',
            field=models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(message='Expiry date must be in MM/YY format.', regex='^\\d{2}/\\d{2}$')]),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('Credit Card', 'Credit Card'), ('Debit Card', 'Debit Card')], max_length=100),
        ),
    ]
